"""updated scraped contacts urls table

Revision ID: 736c398f63be
Revises: db4957489a10
Create Date: 2025-06-13 11:53:34.099051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '736c398f63be'
down_revision: Union[str, None] = 'db4957489a10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('scraped_contacts', 'urls',
               existing_type=mysql.VARCHAR(length=50),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('scraped_contacts', 'urls',
               existing_type=mysql.LONGTEXT(),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)
    # ### end Alembic commands ###
