"""update string to longtext in scraped contacts table

Revision ID: ac0e29e2e0d1
Revises: f166ddfaddda
Create Date: 2025-06-12 12:20:55.755441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ac0e29e2e0d1'
down_revision: Union[str, None] = 'f166ddfaddda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('scraped_contacts', 'emails',
               existing_type=mysql.VARCHAR(length=200),
               type_=mysql.LONGTEXT(),
               existing_nullable=False)
    op.alter_column('scraped_contacts', 'phones',
               existing_type=mysql.VARCHAR(length=200),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('scraped_contacts', 'phones',
               existing_type=mysql.LONGTEXT(),
               type_=mysql.VARCHAR(length=200),
               existing_nullable=True)
    op.alter_column('scraped_contacts', 'emails',
               existing_type=mysql.LONGTEXT(),
               type_=mysql.VARCHAR(length=200),
               existing_nullable=False)
    # ### end Alembic commands ###
