"""updated scraped contacts table

Revision ID: db4957489a10
Revises: ac0e29e2e0d1
Create Date: 2025-06-13 11:48:51.131631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'db4957489a10'
down_revision: Union[str, None] = 'ac0e29e2e0d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scraped_contacts', sa.Column('site', sa.String(length=50), nullable=True))
    op.add_column('scraped_contacts', sa.Column('urls', sa.String(length=50), nullable=True))
    op.add_column('scraped_contacts', sa.Column('social_links', mysql.LONGTEXT(), nullable=True))
    op.drop_column('scraped_contacts', 'url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scraped_contacts', sa.Column('url', mysql.VARCHAR(length=50), nullable=True))
    op.drop_column('scraped_contacts', 'social_links')
    op.drop_column('scraped_contacts', 'urls')
    op.drop_column('scraped_contacts', 'site')
    # ### end Alembic commands ###
